name: Scala CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run tests with Pekko 1.0.x and Scala 2.12,2.13,3.0
        run: sbt +test
